//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngkorColor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.Guid ID { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ProductDesc { get; set; }
        public Nullable<System.Guid> ProductBrand { get; set; }
        public Nullable<System.Guid> ProductCategory { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Picture { get; set; }
        public Nullable<System.Guid> Type { get; set; }
        public string Size { get; set; }
        public Nullable<System.Guid> Color { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Color Color1 { get; set; }
    }
}
